// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package snippets

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestItem struct {
	ID        int32              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}
