# .github/dependabot.yml
# Basic Dependabot configuration for Go modules

version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    # Look for `go.mod` file in the root directory
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "weekly"